### ISSUE TITLE
Data splits

### ISSUE THREAD

**Issue by yqxian** [YU1ut/imprinted-weights#1]
Thanks for sharing your codes. But how do you handle the data splits? It seems that your data loader always reads all the images from the same directory regardless of the train or validation. Can you explain?

**Comment by YU1ut** [comment]
I used the default train/test split, which is defined by ```train_test_split.txt``` in CUB-200-2011 dataset. 
It is a file like
```
AAA.jpg 0
BBB.jpg 1
CCC.jpg 1
```
1 for train and 0 for test.

I just read this file by pandas and extracted train/test data by these lines in ```loader.py```.
https://github.com/YU1ut/imprinted-weights/blob/master/loader.py#L21-L23
