### ISSUE TITLE
Running error in imprint_ft

### ISSUE THREAD

**Issue by chenxy99** [YU1ut/imprinted-weights#2]
Thanks for sharing your codes. After running the pretrain.py, I start to run the imprint_ft.py. But there are some error messages in 
train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=args.batch_size, sampler=train_dataset.get_balanced_sampler(),
        num_workers=args.workers, pin_memory=True).

And the messages are:
Epoch: [1 | 90] LR: 0.000100
Traceback (most recent call last):
  File "/media/sde/xychen/imprinted-weights/imprint_ft.py", line 335, in <module>
    main()
  File "/media/sde/xychen/imprinted-weights/imprint_ft.py", line 150, in main
    train_loss, train_acc = train(train_loader, model, criterion, optimizer, epoch)
  File "/media/sde/xychen/imprinted-weights/imprint_ft.py", line 235, in train
    for batch_idx, (input, target) in enumerate(train_loader):
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/sde/xychen/imprinted-weights/loader.py", line 65, in __getitem__
    item = self.imgs.iloc[index]
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1738, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1715, in _get_list_axis
    return self.obj.take(key, axis=axis, convert=False)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/generic.py", line 1928, in take
    convert=True, verify=True)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/internals.py", line 4011, in take
    axis=axis, allow_dups=True)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/internals.py", line 3897, in reindex_indexer
    for blk in self.blocks]
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/internals.py", line 3897, in <listcomp>
    for blk in self.blocks]
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/internals.py", line 1046, in take_nd
    allow_fill=True, fill_value=fill_value)
  File "/home/xychen/anaconda3/envs/my_env_1/lib/python3.6/site-packages/pandas/core/algorithms.py", line 1458, in take_nd
    out_shape[axis] = len(indexer)
TypeError: len() of unsized object

From my point of view, it may be caused by the version of pandas I use (Version 0.20.3). So I would like to know which version of pandas you use?
Or it may be caused by any other error setting?

Best Regards,
Xianyu Chen.

**Comment by YU1ut** [comment]
I am using pandas 0.22.0. Could you try it?

**Comment by chenxy99** [comment]
Thank you very much. I can run your code successfully.

**Comment by MathildaChen** [comment]
> Thank you very much. I can run your code successfully.

Hello, Chen. I meet the same problem as you. But using pandas 0.22.0 doesn't settle it. Can you tell me how you solve the problem?
My environment is:
cudatoolkit               9.0                  h13b8566_0    defaults
cudnn                     7.1.2                 cuda9.0_0    defaults
cycler                    0.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dbus                      1.10.20                       0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
expat                     2.1.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fontconfig                2.12.1                        3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
glib                      2.50.2                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gst-plugins-base          1.8.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gstreamer                 1.8.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icu                       54.1                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
intel-openmp              2019.1                      144    defaults
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc                    5.2.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libpng                    1.6.30                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxcb                    1.12                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libxml2                   2.9.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
matplotlib                2.0.2               np113py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py36h7dd41cf_0    defaults
mkl_random                1.0.1            py36h4414c95_1    defaults
nccl                      1.3.5                 cuda9.0_0    defaults
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numpy                     1.13.3           py36hdbf6ddf_4    defaults
numpy-base                1.15.4           py36h81de0dd_0    defaults
olefile                   0.44                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandas                    0.22.0           py36hf484d3e_0    defaults
pcre                      8.39                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pillow                    4.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
progress                  1.4                      py36_0    defaults
pycparser                 2.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyqt                      5.6.0                    py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python                    3.6.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.6.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytorch                   0.4.1            py36ha74772b_0    defaults
pytz                      2017.2                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qt                        5.6.2                         5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sip                       4.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
torchvision               0.2.1                    py36_0    defaults
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by chenxy99** [comment]
Hello, MathildaChen. It is because the version of your pytorch is 0.4.1. You need to degrade your pytorch to version 0.4.0.

**Comment by YU1ut** [comment]
Hello, MathildaChen. Could you try pandas 0.23.4? I ran it successfully with pandas 0.23.4 and pytorch 0.4.1 .

**Comment by flexibility2** [comment]
> Thanks for your source code, however I meet the same problem with pandas 0.23.4 and pytorch 0.4.1.
and I can't figure out what's the relationship with pandas. Thanks for your generosity!

(/data/wuxiaotian/pt0.4.1) wuxiaotian@ubuntu14x64:/data/wuxiaotian/dataset/imprinted$ python imprint_ft.py --model pretrain_checkpoint/model_best.pth.tar --num-sample 1
==> Reading from model checkpoint..
=> loaded model checkpoint 'pretrain_checkpoint/model_best.pth.tar' (epoch 75)
Imprinting |################################| (2/2) Data: 0.000s | Batch: 0.953s | Total: 0:00:02 | ETA: 0:00:03
    Total params: 24.08M

Epoch: [1 | 90] LR: 0.000100
Traceback (most recent call last):
  File "imprint_ft.py", line 335, in <module>
    main()
  File "imprint_ft.py", line 150, in main
    train_loss, train_acc = train(train_loader, model, criterion, optimizer, epoch)
  File "imprint_ft.py", line 235, in train
    for batch_idx, (input, target) in enumerate(train_loader):
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/wuxiaotian/dataset/imprinted/loader.py", line 65, in __getitem__
    item = self.imgs.iloc[index]
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexing.py", line 2091, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexing.py", line 2070, in _get_list_axis
    return self.obj._take(key, axis=axis)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/generic.py", line 2789, in _take
    verify=True)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/internals.py", line 4537, in take
    new_labels = self.axes[axis].take(indexer)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2195, in take
    return self._shallow_copy(taken)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexes/range.py", line 267, in _shallow_copy
    return self._int64index._shallow_copy(values, **kwargs)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexes/numeric.py", line 68, in _shallow_copy
    return self._shallow_copy_with_infer(values=values, **kwargs)
  File "/data/wuxiaotian/pt0.4.1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 538, in _shallow_copy_with_infer
    if not len(values) and 'dtype' not in kwargs:
**TypeError: object of type 'numpy.int64' has no len()**


Name                    Version                   Build  Channel
absl-py                   0.5.0                     <pip>
astor                     0.7.1                     <pip>
backcall                  0.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2018.03.07                    0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2018.8.24                py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                    <pip>
decorator                 4.3.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.2.0                     <pip>
grpcio                    1.15.0                    <pip>
ipython                   6.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipython_genutils          0.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jedi                      0.12.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.0.1                     <pip>
libedit                   3.1.20170329         h6b74fdf_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Markdown                  3.0                       <pip>
matplotlib                3.0.0                     <pip>
ncurses                   6.1                  hf484d3e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.14.5                    <pip>
openssl                   1.0.2p               h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pandas                    0.23.4                    <pip>
parso                     0.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pexpect                   4.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pickleshare               0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Pillow                    5.2.0                     <pip>
pip                       18.1                      <pip>
pip                       10.0.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
progress                  1.4                       <pip>
progressbar               2.5                       <pip>
prompt_toolkit            1.0.15                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
protobuf                  3.6.1                     <pip>
ptyprocess                0.6.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pygments                  2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 2.2.1                     <pip>
python                    3.6.6                hc3d631a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.7.3                     <pip>
pytz                      2018.7                    <pip>
readline                  7.0                  h7b6447c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scikit-learn              0.20.1                    <pip>
scipy                     1.1.0                     <pip>
setuptools                40.2.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                39.1.0                    <pip>
simplegeneric             0.8.1                    py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.11.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sklearn                   0.0                       <pip>
sqlite                    3.24.0               h84994c4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               1.10.0                    <pip>
tensorboard-logger        0.1.0                     <pip>
tensorflow                1.10.1                    <pip>
termcolor                 1.1.0                     <pip>
tk                        8.6.8                hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     0.4.1                     <pip>
torchvision               0.2.1                     <pip>
tqdm                      4.26.0                    <pip>
traitlets                 4.3.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wcwidth                   0.1.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.4                h14c3975_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               ha838bed_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by YU1ut** [comment]
@flexibility2 
Thank you for reporting this to me.
Does changing the line `item = self.imgs.iloc[index]` in loader.py to 
`item = self.imgs.iloc[int(index)]` solve your problem?

**Comment by flexibility2** [comment]
@YU1ut Thanks for your generosity, you are right. Just one more question that I can't figure out, so I want to discuss with you. I notice that you didn't implement the experiment of **Transfer Learning with Imprinted Weights** in the **"6.3 Results "** of the paper. However, do you think what the difference between the result of **Table 3** and **Table 1** in detail?
I am looking forward for your reply!

**Comment by YU1ut** [comment]
@flexibility2 
In my opinion, the difference between the results of **Table 3** and **Table 1** is that **Table 1** shows the accuracy of a 200-way classifier but  **Table 3** shows the accuracy of a 100-way classifier. In a **Transfer Learning** manner, authors used 100 base classes to train a classifier and then trained it again only on 100 novel classes with few samples. As a result, **Table 3** shows that initializating the final layer parameters by imprinting is better than with random values.
